feat: add landing page
faast-rt/docs pull request #2
Opened 2023-10-23 14:54 UTC by iverly

This PR adds the landing page for the documentation website.

2023-10-23 15:20 UTC, nponsard approved these changes

2023-10-23 16:13 UTC, alexis-langlet requested changes
Could you please add space on top of the big title so that you only see that when you land on the page ? 

Also, in the sentence: 
"Experience seamless integration, swift deployments, and a robust ecosystem designed to supercharge your applications. Elevate your serverless journey with us."
Seems a bit too much, could you please change the "a robust ecosystem designed to supercharge your applications" part pls?

The dark mode is maybe a bit too black and that looks weird. 

Other than that it's perfect, really good work!

2023-10-24 06:55 UTC, iverly commented
> Could you please add space on top of the big title so that you only see that when you land on the page ?
> 
> Also, in the sentence: "Experience seamless integration, swift deployments, and a robust ecosystem designed to supercharge your applications. Elevate your serverless journey with us." Seems a bit too much, could you please change the "a robust ecosystem designed to supercharge your applications" part pls?
> 
> The dark mode is maybe a bit too black and that looks weird.
> 
> Other than that it's perfect, really good work!

Changes done, the dark mode will be fixed in the future since it's not the priority right now. (and it's working)

2023-10-24 07:03 UTC, alexis-langlet approved these changes
Good for me!
Really nice job, thank you

2023-10-24 07:08 UTC, merged